services:
  mongo:
    image: mongo:8.0
    container_name: mongodb_prisma
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - mongo_keyfile:/data/keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    entrypoint:
      - bash
      - -c
      - |
        if [ ! -f /data/keyfile/mongo-keyfile ]; then
          openssl rand -base64 756 > /data/keyfile/mongo-keyfile
          chmod 400 /data/keyfile/mongo-keyfile
          chown 999:999 /data/keyfile/mongo-keyfile
        fi
        exec docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --keyFile /data/keyfile/mongo-keyfile
volumes:
  mongo_data:
  mongo_keyfile:
